### ISSUE TITLE
Feature request: square size on block page

### ISSUE THREAD

**Issue by rootulp** [celenium-io/celenium-interface#34]
On https://celenium.io/block/835216 it would be cool to see details on the size of the original data square (ODS). I think this would involve indexing some custom metadata because AFAIK the square size is not written to the raw block data. 

The square size is `k` in this snippet

> We want to arrange this data into a k * k matrix of fixed-sized [shares](https://celestiaorg.github.io/celestia-app/specs/shares.html), which will later be committed to in [Namespace Merkle Trees (NMTs)](https://github.com/celestiaorg/nmt/blob/v0.16.0/docs/spec/nmt.md) so that individual shares in this matrix can be proven to belong to a single data root. k must always be a power of 2 (e.g. 1, 2, 4, 8, 16, 32, etc.) as this is optimal for the erasure coding algorithm.

Ref: https://celestiaorg.github.io/celestia-app/specs/data_square_layout.html

**Comment by vvuwei** [comment]
Hey, @rootulp! Thanks for the heads-up on that interesting suggestion! Adding the ODS size would be a great addition for advanced users. You're spot on about the custom metadata - we'll need to explore that option.  We'll definitely prioritize this and keep you in the loop on any updates or decisions.

Thanks again for the feedback!

**Comment by vvuwei** [comment]
released.

**Comment by vvuwei** [comment]
released.
