### ISSUE TITLE
Feature request: original data square visualizer

### ISSUE THREAD

**Issue by rootulp** [celenium-io/celenium-interface#35]
Currently, there isn't an easy way to visualize the original data square of a Celestia block. It would be nice if the block page contained a visualization of the shares in the original data square. The end result would look something like this: 

<img width="152" alt="ods-visualization" src="https://github.com/celenium-io/celenium-interface/assets/3699047/7c697798-c6cf-417e-b847-a697c1142388">

with unique colors per namespace. We could special-case the reserved namespaces so they always use the same color.

**Comment by vvuwei** [comment]
Hey @rootulp! Definitely agree it would be awesome to see the shares laid out visually, just like you described. Unique colors per namespace with reserved ones having special treatment sounds like a interesting idea. We'll definitely explore this and keep you posted on any updates or decisions made.

Btw, do you think namespaces will be as much informative as making colors per registered rollup? 

Thanks again for the suggestion! 🙏

**Comment by rootulp** [comment]
> Btw, do you think namespaces will be as much informative as making colors per registered rollup?

Roll-ups registering their own color seems like a cool idea. If a roll-up hasn't registered a color, we may want to deterministically derive one based on the namespace.

**Comment by myrtleTree33** [comment]
I'm just wondering why would this be important though? What can it be used? It just seems to be what Wireshark does.

**Comment by rootulp** [comment]
A square visualization is primarily useful to developers and not end users. Developers may be interested in where a particular blob landed in a data square because there are a number of proofs that developers / roll-ups use to determine that a blob was actually included in a Celestia data square. The proofs use binary Merkle trees and namespace Merkle trees to prove that some range of shares exist in a Celestia data square and the location in the square has implications on which sibling nodes are needed in the proof.

Additionally live visualizations may be useful for contributors who want to improve the padding rules in Celestia's data square layout.

**Comment by vvuwei** [comment]
released in v1.13.

**Comment by rootulp** [comment]
This feature is so awesome. It's even cooler than I expected. Thanks!
