### ISSUE TITLE
No rollups found on mainnet

### ISSUE THREAD

**Issue by rootulp** [celenium-io/celenium-interface#65]
In the past, I found the rollups tab super useful. Now it shows "No rollups found". Any ideas why it isn't populating for me?

Ref: https://celenium.io/rollups

## Screenshot

![Screenshot 2024-06-27 at 10 09 22 AM](https://github.com/celenium-io/celenium-interface/assets/3699047/073a543c-a7cf-49b2-8f32-a05820f7f773)

**Comment by GusevPM** [comment]
Hi!
It should be fixed now.

Thanks for letting us know❤️

**Comment by rootulp** [comment]
Awesome thanks! Confirmed it looks fixed.
